### ISSUE TITLE
game中に画面がかわったらdisconnectするかしないか

### ISSUE THREAD

**Issue by Chanmachan** [scandamus/ft_transcendence#101]

**Comment by hachi868** [comment]
重複してると思われるIssueあったのでここに集約します

https://github.com/scandamus/ft_transcendence/issues/75 gameのdisconnectの際の処理
> disconnectされてもゲームが切断されないようにする

https://github.com/scandamus/ft_transcendence/issues/28 試合中断時の処理
> 落ちた方が負け？（落ちた判定どうするか？）
> 落ちたら強制0点、としてもscoreで勝敗が決まらない場合がある。
> game_matchに勝敗を格納するfieldが必要かも

**Comment by hachi868** [comment]
できれば再接続して続行したい

**Comment by hachi868** [comment]
意図的なexit => score-1にしてソケットきる
意図しない退出 => ログインで再接続
全員いなくなったらmatchごとdelete
意図せずとしても全員いなくなった => delete

**Comment by Chanmachan** [comment]
#212

**Comment by Chanmachan** [comment]
#290

**Comment by hachi868** [comment]
#286 にて
