### ISSUE TITLE
フレンド一覧中のオフラインメンバーの表示

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#106]
オフラインの人はグレーにする？
少なくとも対戦するボタンは非表示にしたい

**Comment by hachi868** [comment]
関連しそう
https://github.com/scandamus/ft_transcendence/issues/64 getUserList => WebSocket経由のfriendリストに変更

**Comment by monksoffunk** [comment]
Playerクラスにonlineフィールドを追加
シリアライザに追加

**Comment by hachi868** [comment]
`frontend/static_vol/js/modules/friendList.js`に仮の処理が入っています
https://github.com/scandamus/ft_transcendence/pull/136#discussion_r1660128832

onlineフィールドの値に応じて
onlineStatusをonline/ offline / busy切り替えると
avatar右下の丸の色、ボタンのenable/disableが変わります

**Comment by monksoffunk** [comment]
ビジー見送り
