### ISSUE TITLE
router() には何を渡すの？

### ISSUE THREAD

**Issue by snara-42** [scandamus/ft_transcendence#107]

**Comment by hachi868** [comment]
ログイン状況をboolで渡してました。
（それに応じて`router()`内部の処理を変えている）

- ログインしている => `true`
- ログインしていない => `false`

**Comment by hachi868** [comment]
決めうちで`true/false`渡している箇所、accessTokenを渡すことでtrueと判定させている箇所とあるのですが
accessTokenを使って何かしてるわけではないので
`true/false`に揃えた方が良いかもしれません

```
router(data);
```
↓dataのt/f判定を外部に
```
if(data) {
  router(true);
}
```

**Comment by snara-42** [comment]
言語設定を変えたときに、どのページにいても再読み込みするにはどうするのがいいですか？

**Comment by hachi868** [comment]
`#languageSelect`の`onChange`時の処理に`router(true)`すると再描画かかると思います
```
    // 言語が変更されたときの処理
    languageSelect.addEventListener('change', () => {
        const selectedLanguage = languageSelect.value;
        console.log('!selectedLanguage! ' + selectedLanguage);
        localStorage.setItem('configLang', selectedLanguage);
        //↓こういう
        router(true).then(() => {});
    });
```
他では移動先をpushStateしてURL書き換えた上で、routerでそのURLに該当するviewを描画していますが
pushStateせずrouter叩くと現在のURLを描画するはず

**Comment by hachi868** [comment]
`router()`内部でtoken取得するのも丁寧ではあるけれど、
ログイン、ログアウトの後処理の遷移の場合は過剰になってしまう

**Comment by snara-42** [comment]
ログインしていたら `router(true)`
ログアウト状態なら `router(false)` 
ログイン状態に関わらず 現在のURLを再描画するには
`router(getToken())` みたいにするのがいいですか？

**Comment by hachi868** [comment]
> router(getToken()) みたいにするのがいいですか？

現時点、それがOKと思います！

- token次第で、`router()`内部でリダイレクトかかる可能性があります
- `true/false`で渡すよう、後に方針を揃えるかもしれません
