### ISSUE TITLE
switchlanguageに関わる挙動不審

### ISSUE THREAD

**Issue by snara-42** [scandamus/ft_transcendence#109]
・router() で再読み込みすると languageSelect が English に戻ってしまう
・ブラウザのキャッシュのせいで切り替わらないことがある
（switchlanguage してから hard reload してもそのまま? ）

**Comment by hachi868** [comment]
ページload、switchLanguage時に選択した言語に`selected`をつけて初期値にしたい
https://developer.mozilla.org/ja/docs/Web/HTML/Element/option#selected

**Comment by snara-42** [comment]
>・router() で再読み込みすると languageSelect が English に戻ってしまう

#128 で表面的に解決かも
