### ISSUE TITLE
TODO: プレイヤー名表示

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#112]
ゲーム中のプレイヤー名をユーザー名（トーナメント中は設定したエリアス）に

**Comment by monksoffunk** [comment]
@Chanmachan 対応お願いできますか？
ゲームコンテナ側からクライアントに送るor backendから送るのどちらかで取得できます

**Comment by hachi868** [comment]
プレイヤー名に加えavatarを表示したいのと、
4人プレイのスタイリングをやりたいので一旦こちらで預かります！

**Comment by hachi868** [comment]
もしやりかけだったら後にmergeしましょう
