### ISSUE TITLE
TODO: ballの角度によってpaddleを動かさないと一生終わらないことがある

### ISSUE THREAD

**Issue by Chanmachan** [scandamus/ft_transcendence#120]
プレーヤー二人が画面移動した場合、裏で永遠にwebsocketがsend,receiveし続ける可能性
- 制限時間つけるとか
- そもそもballをいじるか

**Comment by hachi868** [comment]
時間制限をつけたとして、同点ならどうするか

**Comment by hachi868** [comment]
friend, lounge matchは同点ならそのまま勝敗つけない

**Comment by hachi868** [comment]
そのままで。
