### ISSUE TITLE
TODO: recommendedからの友達申請

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#123]
表題の対応が必要かと思って画面見直したところ疑問

recommendedって対戦ボタンではなく友達申請か？
<img width="1125" alt="image" src="https://github.com/scandamus/ft_transcendence/assets/16618674/4d0084b7-21f7-4b06-978d-6d6732f7a1af">

**Comment by hachi868** [comment]
ですね、recommendedは友達申請の想定でした

**Comment by hachi868** [comment]
- 直近でLoungeやTournamentで対戦したユーザーで、friendになっていないplayerをリスト表示
- 人数は3人くらい
- ボタンを友達申請にする
