### ISSUE TITLE
ゲームdebug

### ISSUE THREAD

**Issue by hachi868** [scandamus/ft_transcendence#169]
PRとは別で、挙動確認に留まらない細かなチェックを行う

**Comment by Chanmachan** [comment]
quad: 反射角にrandomな要素を持たせてあげないとスタックすることがある(負けた人の壁だけにでも持たせたい)

**Comment by Chanmachan** [comment]
quad: activeではなくなったpaddleの反射は通常のwallと同様に反射させる
