### ISSUE TITLE
[要検討]トーナメントの仕様

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#179]
# トーナメントの仕様について要検討の事項

### トーナメントが重なるとまずい？
複数のトーナメントが重なるという状況は避けたいです。同じPlayerが時間的に重なる可能性のある複数のトーナメントに参加した場合、マッチングが非常に厄介になりますし、そのような事態が起こるシステム設計はよろしくなさそうです
現実的には１日１トーナメントしか設定出来ないなどの制約をつけるとか？
自分がプレイの経験あるオンラインゲームではたいてい運営側しかこの種のイベントは設定できないはずです

### トーナメント表示件数
そもそも現状では一般ユーザーが際限なくトーナメントを作成できてしまうため、制度として許可された行為でサーバーを高負荷にされてしまう問題があります

### リストのアップデート
現状ではfetchしたときしかアップデートをしていません。誰かがトーナメントを作成するとログイン中の全員に通知を飛ばしてfetchさせることは可能ですが、負荷が心配。さらに各トーナメントの参加者数をリアルタイムにアップデートするには、誰かがエントリー／キャンセルするごとに全員に通知を飛ばして一斉にfetchが起こるという恐ろしい仕様になるのでためらっています

### ニックネームの仕様
現状ではusernameに準じた仕様となっている？ようですが、可能なら日本語も対応できるとうれしいかもしれません

**Comment by monksoffunk** [comment]
重複防止策
- トーナメントマッチに時間制限を設ける
- 登録しようとするトーナメントの時刻より一定時間内にほかの登録済みトーナメントが存在しないこと

**Comment by hachi868** [comment]
全体で作れるトーナメント数をかなり絞っても良い気がしてきました。
5件くらいで。

デバッグしていてupcomingが20件くらい並んだ時、
いつ開催にするか決めるにあたって全ての開催日時を目視チェックするのは
時系列に並んでいるとはいえ結構大変ではないかと思います

**Comment by monksoffunk** [comment]
以下まだ仕様も未決定
- [ ] 終了したらオフラインだったPlayerのステータスをwaitingに変更？（未実装）
- [ ] 終了したEntryの扱い。トーナメント終了時に関連するEntryを削除？（未実装）

**Comment by hachi868** [comment]
ref. https://github.com/scandamus/ft_transcendence/issues/25#issuecomment-2198000215 game_matchは終了後に削除する？

> 削除しない方向で検討中
> 一定期間ごとにパーティショニングorアーカイブ？

**Comment by monksoffunk** [comment]
@monksoffunk 
終了したらオフラインだったPlayerのステータスをwaitingに変更する（未実装）
