### ISSUE TITLE
アバターの不整合

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#213]
アバターを変更したのに別のブラウザで見ると変更されないといった現象が発生してます
再現方法
- chromeで新規アカウント作成してログイン
- そのアカウントを使ってsafariでもログイン
- chromeでアバターを設定
- adminで設定されていることを確認
- safariをリロードしてログアウトさせる
- adminを確認するとアバター設定のファイル名が消えている

なおchromeとsafariを入れ替えても同じ結果です

**Comment by hachi868** [comment]
どうやらDBの排他制御の仕業っぽいです。
アバターの他、言語設定でも同じ状況が発生しました。
（https://github.com/scandamus/ft_transcendence/pull/204 このPRのブランチにて）

調べるといろいろ対応策は出てくるのですが
多重ログイン禁止 https://github.com/scandamus/ft_transcendence/issues/72 で対応するのが良さそうかなと思います

**Comment by monksoffunk** [comment]
今回指摘した問題はdisconnect時の処理ですが、どの部分でも発生する可能性があるので根本的には多重ログイン禁止しかないですね（もしくはトランザクションをアトミックにして毎回レコードを読み込むか部分更新にする）

とりあえず以下のように部分更新にすると「多重ログイン時の一方のログアウトで意図しないフィールドまで上書きされる」現象はなくなりますがどうしましょう？
- 現状が気持ち悪いから変更する
- 問題が潜在化するのが怖いからいまはこのまま放置する

```python
            # reset player status
            player = self.player
            if player:
                if player.status in ['friend_waiting', 'lounge_waiting']:
                    player.status = 'waiting'
                    await database_sync_to_async(player.save)(update_fields=['status'])
                #    await database_sync_to_async(player.save)()
                    logger.info(f'{self.user.username} status set to waiting')
                player.online = False
                await database_sync_to_async(player.save)(update_fields=['online'])
                #await database_sync_to_async(player.save)()
                await send_status_to_friends(player, 'offline')
```

**Comment by hachi868** [comment]
ありがとうございます、部分更新効きますね！

部分更新は複数セッションからの更新が起こりうる場合を想定していて
多重ログイン禁止がアトミック性のためとするとちょっと相性良くないかもしれないですね。
ここどうしましょう。。
多重ログインを弾く際、既にログインしていたユーザーのdisconnect=>新しいユーザーのログインの順で処理されるなら、上書きによる不整合は起こり得ないはずなのでそのままでもと思いますが
保存フィールドを更新される箇所のみに絞るのも明示的で良さそうです
