### ISSUE TITLE
TODO: トランザクション競合のチェック

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#214]
多重ログイン以外にトランザクションの競合が起こる可能性がある場所を確認する

**Comment by hachi868** [comment]
https://github.com/scandamus/ft_transcendence/pull/280
気になった箇所のメモをConversationにコメントで残したのですが
他にも多岐に渡りそうです。。

**Comment by monksoffunk** [comment]
Matchのviewsとserializersで重複していた処理は #281 で対応しました

**Comment by monksoffunk** [comment]
考えてみるとユーザー登録が競合しますね
さらに42authを使った場合も絡みます
やっておきます
