### ISSUE TITLE
ログインフォームの無効化

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#244]
#238 により、以下の場合にログインまで5秒待つ状態になります。
- PlayerのonlineがTrueだがwsがつながっていない状態のユーザーがログインを試みた→新しいログインの発生により古いログインのソケットに向けてログアウトを要求→wsが切断しているため反応がない→タイムアウト（5秒）によりonlineをFalseにしてから新しいユーザーにレスポンスを変えす

この間、ログインフォームは生きたままなので次々に異なるログインを行われたり、あるいはボタンを連打される可能性が。
ログインフォームでログインボタンを押した後に入力欄やボタンを無効化した方がよいかも？

**Comment by hachi868** [comment]
これやります
連打を無効化する方向で検討中です

**Comment by hachi868** [comment]
https://github.com/scandamus/ft_transcendence/pull/247 にて対応済み
