### ISSUE TITLE
データベース保存時のフィールド限定

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#246]
基本的にフィールド限定した方がパフォーマンス的にもデータ競合の面でも有利なので、書き換えたいと思っています。
PRが落ち着いた段階で。

#213

**Comment by hachi868** [comment]
アバター変更してもログアウトすると元に戻ってしまうと思ったらこれでした

**Comment by hachi868** [comment]
怪しいところがあれば #214 にメモ

**Comment by hachi868** [comment]
match終了時のstatus保存が`MatchSerializer`,`MatchViewSet`で2重に走ってるかも
