### ISSUE TITLE
マッチ中にトーナメント時間が近づいた際の挙動

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#272]
#134 
####  試合中でもトーナメントマッチの場合のみ強制的に試合放棄の上、トーナメントマッチに遷移させる
の項目

現状ではマッチ中にトーナメントのroomへの移動の通知を受けとると、クライアントはマッチのEXITのモーダルを表示して中断するか続行するかを選択させるようになっていますが、このあたりの挙動をどうすべきか悩んでます

**Comment by hachi868** [comment]
トーナメントへの移動を拒否できる選択肢があると複雑になりそうですね。。
「時間なので棄権して移動します」モーダルを表示するなどして強制リダイレクトしたいです。
トーナメント開始前5分前から「◯時◯分にトーナメントに移動します」など表示しておくと強制感は和らぐでしょうか
