### ISSUE TITLE
Tokenが削除された場合のハンドリング

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#277]
https://github.com/scandamus/ft_transcendence/blob/8491ae4b75252d5da4262d47ea3ff5216c825f1b/frontend/static_vol/js/modules/token.js#L5-L13

nullだとスローされるがキャッチしていないため、言語選択やfetchUploadAvatarなどgetTokenを直接呼んでいてキャッチしていない部分が問題になりそうです。
![image](https://github.com/user-attachments/assets/569c5ff9-30a0-4560-a918-12f827e06cf9)

**Comment by hachi868** [comment]
- [ ] fetchUserInfo
- [ ]fetchLevel
- [ ]fetchUploadAvatar
- [ ]fetchFriendRequests
- [ ]updateDbLang
- [ ]fetchFriends
- [ ]fetchRecommend
- [ ]fetchMatchLog
- [ ]fetchLogout
- [ ]fetchTournaments
- [ ]fetchTournamentDetail
