### ISSUE TITLE
dual:対戦中に故意でexitしたら負け、故意ではなく二人とも落ちたらマッチを終了

### ISSUE THREAD

**Issue by Chanmachan** [scandamus/ft_transcendence#286]
故意のexit vs 故意ではない切断orリロード => exit側の負け
故意ではない切断orリロード vs 故意ではない切断orリロード => 対戦終了でplayer1の勝ち

**Comment by monksoffunk** [comment]
故意ではない双方のリロードや切断→そのときの点数で決まる（同点だとplayer1が勝ち）
