### ISSUE TITLE
トーナメント時間のバリデ

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#296]
作成画面でいったんNGな時刻を入れると、それ以降、通るはずの時刻にしてもフロントのバリデで蹴られるようです
<img width="1132" alt="image" src="https://github.com/user-attachments/assets/0f3ebd03-38fa-4d55-afcc-d9e0a410b323">

**Comment by hachi868** [comment]
すみません、これ手元で発生しないようでして。
バリデーションの実行タイミングがフォームへのフォーカスを外したタイミングなので
もしフォーカスした状態で時刻変更してもエラーのままということであれば、仕様なのですみません。。
フォーカスを外してもエラーが消えない場合、画像の例だと14:00以前なら通るはずです

**Comment by hachi868** [comment]
環境によって標準時で判定されていそう
