### ISSUE TITLE
ユーザーのレベル判定

### ISSUE THREAD

**Issue by hachi868** [scandamus/ft_transcendence#32]
考慮する際に活用できそうな要素

* 試合数
* 勝ち数(もしくは勝率)
* ペナルティ
* フレンド数
* 対戦の承諾率

いっそ、(勝ち数 / 総試合数) があるのでそれで十分かもしれません

**Comment by monksoffunk** [comment]
単純な指標としての案
- 勝数だけで判断

**Comment by hachi868** [comment]
勝ち数だけで決まるとすると、`Player` => `level`フィールドが不要になりますね

**Comment by hachi868** [comment]
https://github.com/scandamus/ft_transcendence/pull/199
仮にlevel = 勝ち数×0.2

トーナメントを考慮しないなら、係数をどうするかの検討のみ

**Comment by hachi868** [comment]
トーナメント結果をlevelに加味するとして
トーナメントでも勝つごとに `level += 0.2`するとかならシンプルな処理で済みそう
（Playerの勝ち数は従来通りLounge, Friend matchのみ加算）
