### ISSUE TITLE
token_blacklistのマイグレーション

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#50]
# マイグレーション不完全問題

token_blacklistのマイグレーションが不全となる問題

2つのコンテナでデータベースを共有していることが問題になっている模様。pong-serverからの直接データベース操作をなくしてAPIアクセスへと変更することで解決するかどうか要確認

              posgre dir削除してまっさらな状態からbuildした時、
token_blacklist用のtableがなぜか作られないようです。
力技ですがtoken_blacklistだけ後追いでmigrateすると作成されるようです。
（※一旦停止して立ち上げ直しても作成されますが、必要なものは初回で構築されて欲しいので）

更新箇所から行数的に離れていたせいか、suggestにできなかったのでコメントにて。

L17-18
```
python manage.py makemigrations
python manage.py migrate
```
↓ `migrate token_blacklist`追加
```
python manage.py makemigrations
python manage.py migrate
python manage.py migrate token_blacklist
```

_Originally posted by @hachi868 in https://github.com/scandamus/ft_transcendence/pull/47#discussion_r1617325951_

**Comment by hachi868** [comment]
`backend`、`pong-server`のmigrateが走る順番によるかもしれない気がしつつ
納得できる推測が考えつきません

- tokenのblacklist機能は`backend`、`pong-server`の両方で使い、両方とも下記が走る
```
python manage.py makemigrations
python manage.py migrate
```
- settingで`INSTALLED_APPS` に`rest_framework_simplejwt.token_blacklist`を追加しているのは`backend`
- migrationの最後で`python manage.py migrate token_blacklist`するとうまくいく（と言えるかはさておき）

`backend`でしかtoken_blacklistの`makemigrations``migrate`が実行されないのはわかるとして
テーブルが作られない理由がわからない。
なんらかの理由で作られた後に消えているかもしれない？

playerテーブルがうまく作られなかったのは`backend`、`pong-server`の順にmigrateが走って
`pong-server`のmigrationで上書きしてたと考えると納得がいきます

**Comment by monksoffunk** [comment]
pong-serverはデータベースを直接触らない方向にしたため、少なくともコンテナ間の競合は排除できます。

現在のようにテーブルに変更のあるブランチを同じデータベースボリュームのままプルしてテストしているとマイグレーションとデータベースとのテーブル不整合が起こっているような気もします。

最終的にはデータベースを空にしてマイグレーションを実行し、マイグレーションディレクトリを含めてマージすればよい？
これ以降も随時チェックしていきましょう。
