### ISSUE TITLE
関数名重複 `loadGameContent()`

### ISSUE THREAD

**Issue by hachi868** [scandamus/ft_transcendence#68]
`loadGameContent()`関数が2つあるので、どちらかrename、もしくは削除した方が良いかもしれません

- file: `/frontend/static_vol/js/modules/websocket.js`
  L60 (`class WebSocketManager` のmethod。現時点で未使用)
 
 - file: `/frontend/static_vol/js/modules/websocketHandler.js`
 L40

**Comment by monksoffunk** [comment]
これなんで書いたのかまったく記憶にないので完全無料

修正します
