### ISSUE TITLE
modalを二重に開かないようにする

### ISSUE THREAD

**Issue by hachi868** [scandamus/ft_transcendence#69]
すでにmodalが開いていたら、開かない（reject扱い）

**Comment by monksoffunk** [comment]
backendでは #137 で一部対応
トーナメント時はまだ未対応

クライアント側での対応が必要かは要検討

**Comment by hachi868** [comment]
[ ] `replaceView()`でモーダルを閉じているので、ページ移動したら閉じられている。

### `showModal()`の呼び出し元について。

- [ ] `showModalSendMatchRequest()`
フレンドマッチの送信モーダル
`updateFriendsList()`=>dashboard, friendで使用
すでに相手がフレンドマッチ受け取り済み、ラウンジマッチ待機中、対戦中ならbackendで`playerNotWaitingStatus`、リクエストを送らないようにしている https://github.com/scandamus/ft_transcendence/pull/156

- [ ] `showModalReceiveMatchRequest()`
フレンドマッチの受信モーダル
上と対。送られない。

- [ ] `showModalWaitForOpponent()`
ラウンジマッチの対戦相手待ちモーダル

- [ ] `showModalEntryTournament()`
トーナメントエントリーモーダル

- [ ] `showModalExitGame()`
ゲーム進行中に退出しようとすると出現する確認モーダル
`router()`内で呼ばれ、一旦遷移キャンセル。
ゲーム画面に移動する際、`replaceView()`でモーダルは閉じている。
他のモーダルは対戦中には受け取らない。
