### ISSUE TITLE
無効Tokenでログインできてしまう（ように見える）

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#79]
以前にちょっとお話した件に出くわしたので報告

未ログインにもかかわらずSIGN UPを押すと登録画面には遷移せずにログイン状態になってしまう

今回確認したのは#78 でしたが、これにかかわらず起こる可能性がありそうです
LocalStorageのトークン消せば解消します

未ログイン状態でSIGN UPを押したのに名無しログインされたことになってDashboardに遷移する
![image](https://github.com/scandamus/ft_transcendence/assets/16618674/7eddd97c-4f75-4246-a805-c01dddda89aa)

```
users.js:41 getUserList failed: Error: fetchUserList error. status: 403
    at fetchUserList (users.js:28:15)
(anonymous) @ users.js:41
Promise.catch (async)
getUserList @ users.js:40
showUserList @ Dashboard.js:124
(anonymous) @ PageBase.js:24
afterRender @ PageBase.js:24
replaceView @ router.js:87
await in replaceView (async)
router @ router.js:133
(anonymous) @ router.js:62
Dashboard.js:144 getUserInfo failed: TypeError: Cannot read properties of undefined (reading 'map')
    at Dashboard.js:127:43
(anonymous) @ Dashboard.js:144
Promise.catch (async)
showUserList @ Dashboard.js:143
(anonymous) @ PageBase.js:24
afterRender @ PageBase.js:24
replaceView @ router.js:87
await in replaceView (async)
router @ router.js:133
(anonymous) @ router.js:62
```

**Comment by hachi868** [comment]
ログアウトしないでウィンドウを閉じる
（→localStorageのtokenが消されるのはログアウト時なので、tokenはそのまま残る）
→DB, docker imageなどall reset.
→ブラウザでアクセス。tokenが残っているのでアクセス済み扱いにはなるが、システム上は不正なtoken。balcklistにも入っていないのでそこでも弾けない

という可能性ありますか？

**Comment by hachi868** [comment]
#60, #42 もおそらく同種の現象
tokenの有効性を見てからLogInできるように修正
